[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "salon happy crane glow oil describe lake upper enroll napkin right select neck enable genuine sport toss leisure sponsor odor stool napkin rely jaguar"
